[package]
name = "FileExplorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.9.0"
gio = "0.9.0"
glib = "0.10.0"
chrono = "0.4"
libc = "0.2.153"
zip = "0.6.6"
fs_extra = "1.2"
